[pytest]
pythonpath = .
testpaths = tests
addopts =
	-q
	--junitxml=test-results/junit.xml
	--cov=src
	--cov-report=term-missing
	--cov-report=xml:test-results/coverage.xml
	--cov-report=html:test-results/htmlcov
	--json-report
	--json-report-file=test-results/report.json
